### ISSUE TITLE
Get Garage Door sensor working via ESPHome

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pico-w-garage-door-sensor#4]
As the title says. I will need to:

  - [ ] Set up ESPHome integration in Home Assistant
  - [ ] Fill in the `garage-door.yml` configuration so it sends the data to Home Assistant

This issue exists to track the work, document bugs along the way, and have some fun! See related upstream issue: https://github.com/esphome/feature-requests/issues/1924

**Comment by geerlingguy** [comment]
I'm having trouble with WiFi not connecting. I've tried two different Pico W's purchased months apart from different vendors, but get the same thing—it never connects to my home wifi network. See: https://github.com/esphome/feature-requests/issues/1924#issuecomment-1294107720

And if I try the same code:

```yaml
---
esphome:
  name: esp32-test

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

logger:
  level: DEBUG
```

...but on my ESP32 device, it works fine. (To flash, I had to hold BOOT + EN at the same time while doing `esphome run` the first time.) Here's the output when running on ESP32:

```
[17:31:01][C][wifi:037]: Setting up WiFi...
[17:31:01][C][wifi:038]:   Local MAC: 10:52:1C:75:XX:XX
[17:31:01][I][wifi:260]: WiFi Connecting to 'geerling'...
[17:31:07][I][wifi:521]: WiFi Connected!
[17:31:07][C][wifi:365]:   Local MAC: 10:52:1C:75:XX:XX
[17:31:07][C][wifi:366]:   SSID: 'geerling'
[17:31:07][C][wifi:367]:   IP Address: 10.0.100.232
...
```
