### ISSUE TITLE
Add delayed push notification every 10 minutes while garage door is open

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pico-w-garage-door-sensor#5]
This could be annoying during certain times, like when I'm mowing the lawn, but otherwise would be good to have. Maybe also add a motion sensor in the garage to use as a negative indicator in the future, but for now, just a basic `alert` like: https://www.home-assistant.io/integrations/alert/

```yaml
# Example configuration.yaml entry
alert:
  east_garage_door:
    name: East garage door open
    done_message: East garage door closed
    entity_id: input_boolean.east_garage_door
    state: "on"
    repeat: 10
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jeff_phone
```

(Their official example is even based on a Garage Door notification!)
