### ISSUE TITLE
Critical push notification for iPhone/iOS

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pico-w-garage-door-sensor#9]
According to [this comment on YouTube](https://www.youtube.com/watch?v=dFDGtlSi9Eg&lc=UgxH6TLRb1-7njsn-pF4AaABAg), I may be able to make the notification 'critical' in Home Assistant by marking it like:

```yaml
service: notify.mobile_app_phonename
data:
  message: Door open!
  title: Warning!
  data:
    push:
      sound:
        name: default
        critical: 1
        volume: 1
```

I believe I can just throw certain data into the data field / JSON payload in the UI, so I'll see if this makes it work when my phone is in night or focus mode.

**Comment by odinb** [comment]
So, what did you end up with that works in your setup with repeating notifications if door stays open? Full yaml please.

**Comment by geerlingguy** [comment]
I did it all in the visual UI, and here's that:

<img width="1013" alt="Screen Shot 2022-11-26 at 10 46 38 PM" src="https://user-images.githubusercontent.com/481677/204119692-185dd08e-d00c-4742-a2bf-a0ff89c7c526.png">

And here's the YAML:

```
alias: East Garage Door Open
description: ""
trigger:
  - type: opened
    platform: device
    device_id: 0475d8e855b7c087f69d0e1cfc3a0047
    entity_id: binary_sensor.east_garage_door
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition: []
action:
  - service: notify.notify
    data:
      title: East Garage Door open
      message: The East Garage Door is open.
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - repeat:
      until:
        - type: is_not_open
          condition: device
          device_id: 0475d8e855b7c087f69d0e1cfc3a0047
          entity_id: binary_sensor.east_garage_door
          domain: binary_sensor
      sequence: []
mode: single
```
